#!/usr/bin/env python3
"""
Enhanced Eye Tracking Setup Script
This script sets up the YOLOv8 + MediaPipe enhanced eye tracking system
"""

import subprocess
import sys
import os
from pathlib import Path

def run_command(command, description):
    """Run a command and handle errors"""
    print(f"\n🔧 {description}...")
    try:
        result = subprocess.run(command, shell=True, check=True, capture_output=True, text=True)
        print(f"✅ {description} completed successfully")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ {description} failed:")
        print(f"Error: {e.stderr}")
        return False

def check_python_version():
    """Check if Python version is compatible"""
    if sys.version_info < (3.8, 0):
        print("❌ Python 3.8 or higher is required")
        return False
    print(f"✅ Python {sys.version_info.major}.{sys.version_info.minor} detected")
    return True

def install_dependencies():
    """Install required dependencies"""
    print("\n📦 Installing dependencies for enhanced eye tracking...")
    
    # Basic dependencies
    dependencies = [
        "opencv-python>=4.8.0",
        "mediapipe>=0.10.0", 
        "websockets>=11.0",
        "numpy>=1.24.0",
        "scipy>=1.10.0"
    ]
    
    for dep in dependencies:
        if not run_command(f"pip install {dep}", f"Installing {dep.split('>=')[0]}"):
            return False
    
    # Install YOLOv8 (ultralytics)
    print("\n🤖 Installing YOLOv8 (ultralytics)...")
    if not run_command("pip install ultralytics", "Installing YOLOv8"):
        print("⚠️  YOLOv8 installation failed. System will fall back to MediaPipe only.")
    
    return True

def download_yolo_models():
    """Download required YOLO models"""
    print("\n⬇️  Downloading YOLOv8 models...")
    
    try:
        from ultralytics import YOLO
        
        # Download YOLOv8 nano model (smallest, fastest)
        print("Downloading YOLOv8n model...")
        model = YOLO('yolov8n.pt')
        print("✅ YOLOv8n model downloaded successfully")
        
        # Test the model
        print("🧪 Testing YOLOv8 model...")
        import numpy as np
        test_image = np.zeros((640, 640, 3), dtype=np.uint8)
        results = model(test_image, verbose=False)
        print("✅ YOLOv8 model test successful")
        
        return True
    except ImportError:
        print("⚠️  YOLOv8 not available, will use MediaPipe only")
        return False
    except Exception as e:
        print(f"⚠️  YOLOv8 model download failed: {e}")
        return False

def test_camera():
    """Test camera access"""
    print("\n📷 Testing camera access...")
    try:
        import cv2
        cap = cv2.VideoCapture(0)
        if not cap.isOpened():
            print("❌ Cannot access camera (index 0)")
            return False
        
        ret, frame = cap.read()
        if not ret:
            print("❌ Cannot read from camera")
            cap.release()
            return False
        
        h, w = frame.shape[:2]
        print(f"✅ Camera test successful - Resolution: {w}x{h}")
        cap.release()
        return True
    except Exception as e:
        print(f"❌ Camera test failed: {e}")
        return False

def test_mediapipe():
    """Test MediaPipe face detection"""
    print("\n👤 Testing MediaPipe face detection...")
    try:
        import mediapipe as mp
        import numpy as np
        
        mp_face_mesh = mp.solutions.face_mesh
        face_mesh = mp_face_mesh.FaceMesh(
            max_num_faces=1,
            refine_landmarks=True,
            min_detection_confidence=0.5,
            min_tracking_confidence=0.5
        )
        
        # Create a test image
        test_image = np.zeros((480, 640, 3), dtype=np.uint8)
        results = face_mesh.process(test_image)
        
        print("✅ MediaPipe face detection initialized successfully")
        return True
    except Exception as e:
        print(f"❌ MediaPipe test failed: {e}")
        return False

def create_config_file():
    """Create configuration file for the enhanced system"""
    config_content = """# Enhanced Eye Tracking Configuration
# Generated by setup script

# YOLOv8 Settings
YOLO_MODEL = "yolov8n.pt"  # YOLOv8 nano model (fastest)
YOLO_CONFIDENCE = 0.5      # Face detection confidence threshold
YOLO_ENABLED = True        # Enable YOLOv8 face detection

# Enhanced MediaPipe Settings  
MP_MAX_FACES = 1
MP_DETECTION_CONFIDENCE = 0.7
MP_TRACKING_CONFIDENCE = 0.7
MP_REFINE_LANDMARKS = True

# Enhanced Eye Tracking
EYE_TRACKING_ENABLED = True
GAZE_SMOOTHING_WINDOW = 5
SACCADE_THRESHOLD = 0.02
FIXATION_DURATION = 0.3

# Debug Settings
SHOW_YOLO_BOXES = True     # Show YOLO detection boxes
SHOW_GAZE_POINTS = True    # Show gaze estimation points
SHOW_EYE_LANDMARKS = False # Show detailed eye landmarks
ENHANCED_LOGGING = True    # Enable detailed logging
"""
    
    try:
        with open("enhanced_config.py", "w") as f:
            f.write(config_content)
        print("✅ Configuration file created: enhanced_config.py")
        return True
    except Exception as e:
        print(f"❌ Failed to create config file: {e}")
        return False

def main():
    """Main setup function"""
    print("🚀 Enhanced Eye Tracking System Setup")
    print("=" * 50)
    
    # Check Python version
    if not check_python_version():
        sys.exit(1)
    
    # Install dependencies
    if not install_dependencies():
        print("❌ Dependency installation failed")
        sys.exit(1)
    
    # Download YOLO models
    yolo_available = download_yolo_models()
    
    # Test camera
    if not test_camera():
        print("⚠️  Camera test failed - please check camera connection")
    
    # Test MediaPipe
    if not test_mediapipe():
        print("❌ MediaPipe test failed")
        sys.exit(1)
    
    # Create config file
    create_config_file()
    
    # Summary
    print("\n" + "=" * 50)
    print("🎉 Setup Summary:")
    print(f"✅ Python {sys.version_info.major}.{sys.version_info.minor} ready")
    print("✅ Core dependencies installed")
    print("✅ MediaPipe face detection ready")
    print(f"{'✅' if yolo_available else '⚠️ '} YOLOv8 {'ready' if yolo_available else 'not available (will use MediaPipe only)'}")
    print("✅ Configuration file created")
    
    print("\n🎯 Next Steps:")
    print("1. Run: python movements.py")
    print("2. Open the dashboard in your browser")
    print("3. Try the enhanced eye tracking features!")
    
    if yolo_available:
        print("\n🤖 YOLOv8 Features Available:")
        print("- More robust face detection")
        print("- Better performance in challenging lighting")
        print("- Enhanced accuracy for eye tracking")
    else:
        print("\n📝 Note: Running in MediaPipe-only mode")
        print("- Still fully functional with existing features")
        print("- Install ultralytics manually for YOLOv8 features")

if __name__ == "__main__":
    main()